export const REFRESH_TOKEN_KEY = "REFRESH_TOKEN";
export const ACCESS_TOKEN_KEY = "ACCESS_TOKEN";

export const GITHUB_OAUTH_KEY = "GITHUB_OAUTH_KEY";

export const LIGHT_DARK_THEME = "LIGHT_DARK_THEME";
